name: visualgo

networks:
  default:
    name: visualgo-default

services:
  visualgo:
    build:
      context: .
      dockerfile: Dockerfile
      platforms:
        - "linux/amd64"
    pull_policy: build
    image: ivanjsx/visualgo:latest
    container_name: visualgo
    platform: "linux/amd64"
    restart: always
    ports:
      - name: web
        host_ip: 127.0.0.1
        published: "3002"
        target: 80
